{
 "title": "Dasboard-SLI",
 "description": "This dashboard displays information used to observe the Flask application.",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Application stats",
   "type": "table",
   "description": "This panel shows information about the application services.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by (instance, namespace, container) (kube_pod_container_info{container=~\"backend|frontend\"})"
    },
    {
     "expr": "max by (container) (time() - container_start_time_seconds{container=~\"backend|frontend\"})"
    }
   ]
  },
  {
   "title": "Trace jaeger",
   "type": "table",
   "description": "This panel shows information about Trace jaeger",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "service": "backend" }
   ]
  },
  {
   "title": "Successful requests per minute",
   "type": "timeseries",
   "description": "This panel shows the total number of successful requests per service.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count by (container, status) (rate(flask_http_request_duration_seconds_count{container=~\"backend|frontend\",status=~\"200\"}[1m]))",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Error requests per minute",
   "type": "timeseries",
   "description": "This panel shows the total number of 40x and 50x error requests per service.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count by (container, status) (rate(flask_http_request_duration_seconds_count{container=~\"backend|frontend\",status=~\"(^40\\\\d)\"}[1m]))",
     "legendFormat": "{{ container }} (40x)"
    },
    {
     "expr": "count by (container, status) (rate(flask_http_request_duration_seconds_count{container=~\"backend|frontend\",status=~\"(^50\\\\d)\"}[1m]))",
     "legendFormat": "{{ container }} (50x)"
    }
   ]
  },
  {
   "title": "Average response time per minute",
   "type": "timeseries",
   "description": "This panel shows the average response time successful requests (status 200) per service.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(sum(rate(flask_http_request_duration_seconds_sum{container=~\"backend\",status=\"200\"}[1m])) / sum(rate(flask_http_request_duration_seconds_count{container=~\"backend\",status=\"200\"}[1m]))) * 1000\n",
     "legendFormat": "backend"
    },
    {
     "expr": "(sum(rate(flask_http_request_duration_seconds_sum{container=~\"frontend\",status=\"200\"}[1m])) / sum(rate(flask_http_request_duration_seconds_count{container=~\"frontend\",status=\"200\"}[1m]))) * 1000\n",
     "legendFormat": "frontend"
    }
   ]
  },
  {
   "title": "Average memory used per minute",
   "type": "timeseries",
   "description": "This panel shows the average memory used by each service.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(process_resident_memory_bytes{job=\"backend\"}[1m])) * 1e-9",
     "legendFormat": "backend"
    },
    {
     "expr": "- sum(rate(process_resident_memory_bytes{job=\"frontend\"}[1m])) * 1e-9",
     "legendFormat": "frontend"
    }
   ]
  },
  {
   "title": "Average CPU used per minute",
   "type": "timeseries",
   "description": "This panel shows the average CPU used by each service.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{job=\"backend\"}[1m])) * 100",
     "legendFormat": "backend"
    },
    {
     "expr": "sum(rate(process_cpu_seconds_total{job=\"frontend\"}[1m])) * 100",
     "legendFormat": "frontend"
    }
   ]
  },
  {
   "title": "Network I/O Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{node=\"localhost\"}[1m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "-sum(rate(container_network_receive_bytes_total{node=\"localhost\"}[1m]))",
     "legendFormat": "Sent"
    }
   ]
  }
 ]
}